### ISSUE TITLE
Still no DefaultItemWorth: 0 possible on the latest version

### ISSUE THREAD

**Issue by Torben8** [tristankechlo/Tool-Leveling#12]
**Describe the bug**
DefaultItemWorth still can't be 0

**To Reproduce**
1. Change the value in the config to 0
2. Start game
3. value in the config changes back to 10

**Expected behavior**
Value should stay on 0

**Additional context**
This problem should've been fixed in the latest version but isn't

**Comment by tristankechlo** [comment]
Oh yeah, my bad
I marked this on my chekclist as done, but it wasn't.
The newest beta(1.2.2) should fix your issue.
Please test it and let me know

**Comment by tristankechlo** [comment]
should be fixed
