### ISSUE TITLE
Can't put anything in the enchanting slot [MC 1.17.1 / FML 37.0.17]

### ISSUE THREAD

**Issue by General-Radek** [tristankechlo/Tool-Leveling#16]
In the GUI no armor/weapon/tool can be placed in the slot for enchanting. However, anything can be put in the slots for items. Reloading map/server/game doesn't help. No crushes but it is unusable.

**Comment by tristankechlo** [comment]
were the items enchanted, when you tried to put them in?

**Comment by General-Radek** [comment]
No, they weren't. Checked now with enchanted items - works correctly with them. Is this my fault and unenchanted items are not suppozed to work?

**Comment by tristankechlo** [comment]
The table is only for upgrading existing enchantments, so non enchanted items are not allowed in the first slot
