### ISSUE TITLE
Dedicated server crash on startup

### ISSUE THREAD

**Issue by Sixdd6** [tristankechlo/Tool-Leveling#19]
**Describe the bug**
Dedicated server crashes on startup.

**To Reproduce**
Load version 1.2.10 on Forge 36.2.4 dedicated server.

**Expected behavior**
Server to not crash.

**Additional context**
[crash-2021-10-25_21.01.03-fml.txt](https://github.com/tristankechlo/ToolLeveling/files/7414551/crash-2021-10-25_21.01.03-fml.txt)
[debug.log](https://github.com/tristankechlo/ToolLeveling/files/7414552/debug.log)

**Comment by tristankechlo** [comment]
thank you for reporting,
try the newest version (1.2.11), it should fix the problem
