### ISSUE TITLE
Enchantment Value

### ISSUE THREAD

**Issue by Xaikii** [tristankechlo/Tool-Leveling#20]
**Is your feature request related to a problem? Please describe.**
Giving all Enchantments the same Value is not exactly a great feeling, as the difference between a level of Sharpness and a level of Fortune or Looting is huge

**Describe the solution you'd like**
Simply another config that allows to grant each Enchantment a Value

**Describe alternatives you've considered**

**Additional context**

**Comment by tristankechlo** [comment]
I like the idea, will see if I can implement something like this

**Comment by tristankechlo** [comment]
implemented in mod version 1.3.0

**Comment by Xaikii** [comment]
Could this also be added to the 1.16.5 Version?
