### ISSUE TITLE
Config sometimes resets for no reason 

### ISSUE THREAD

**Issue by toffi3** [tristankechlo/Tool-Leveling#25]
I have no clue what are the circumstances for that but it just happens sometimes and i have no clue why. My mod list is down there in this short film

https://youtu.be/1kMY3JxofDc

**Comment by tristankechlo** [comment]
Can you try the newer mod version 1.2.12?  
Either way, the logfile from when the config actually resets would be helpful

**Comment by toffi3** [comment]
https://pastebin.com/qM7r3qGs i assume that this is the one but i am not sure. As i said it happened like 2 times and it did very randomly

**Comment by tristankechlo** [comment]
Well, the I found nothing in the logs...  
Have you tried the newer forge and modversion?
