### ISSUE TITLE
Is it possible to add tools from another mod ?

### ISSUE THREAD

**Issue by gragonfire242002** [tristankechlo/Tool-Leveling#26]
mod tool enchantments don't work all the time

**Comment by tristankechlo** [comment]
which modversion?  
which forge/fabric version?  
what is the name of the mod that won't work?

**Comment by gragonfire242002** [comment]
modversion : 1.17.1
Forge
SuperTools-1.0_1.17.1

**Comment by tristankechlo** [comment]
there are no problems with supertools for me  
I am using:
 - Forge `37.1.1`
 - SuperTools `1.0_1.17.1`
 - ToolLeveling `1.17.1-1.2.12`

**Comment by gragonfire242002** [comment]
I specify that I use forge on a server created with forge

**Comment by gragonfire242002** [comment]
On which site did you take the toolleveling mod and the super tools mod ?

**Comment by tristankechlo** [comment]
I tested on a server too  
both mods need to be installed on the client and the server

**Comment by gragonfire242002** [comment]
Weird my mod works on basic objects on minecraft but not on supertools

**Comment by gragonfire242002** [comment]
I just tried the super pickaxe does not work but the special cup works

**Comment by tristankechlo** [comment]
are both of them enchanted? because you can only put enchanted items in the upgrade slot

**Comment by gragonfire242002** [comment]
Yes the 2 tools are enchanted but the super pickaxe works with no enchantment except minecraft

**Comment by tristankechlo** [comment]
which enchantments are on the pickaxe?

**Comment by gragonfire242002** [comment]
mending ( good )
fortune ( not good)
unbreaking ( not good )
efficiency ( not good )

**Comment by tristankechlo** [comment]
are you sure they are not blacklisted in the config?  
are there enough payment items in the table?  
can you upload a screenshot of the table gui with the pickaxe in it?

**Comment by gragonfire242002** [comment]
<img width="201" alt="Capture d’écran 2022-02-22 165324" src="https://user-images.githubusercontent.com/100018940/155170912-c1aa7255-b873-44bf-93ac-45e623aaf401.png">
<img width="541" alt="Capture d’écran 2022-02-22 170109" src="https://user-images.githubusercontent.com/100018940/155170916-a9a14aba-032a-40cf-8f69-34d08d850a0b.png">
<img width="418" alt="Capture d’écran 2022-02-22 170131" src="https://user-images.githubusercontent.com/100018940/155170917-968ecbd0-85cb-4319-8560-60b37c44b5f1.png">

**Comment by gragonfire242002** [comment]
My game in french

**Comment by tristankechlo** [comment]
and when click on one of the buttons, the upgrading only works for mending,  
and not for fortune, unbreaking or efficiency?  
if so, can you send me the log files?  
which mod adds the extra buttons in the top right corner?

**Comment by gragonfire242002** [comment]
[2022-02-22-4.log](https://github.com/tristankechlo/ToolLeveling/files/8118266/2022-02-22-4.log)

**Comment by gragonfire242002** [comment]
The mod to add is Inventory Profiles Next

**Comment by gragonfire242002** [comment]
Mending not being improvable in minecraft there is no improvement difference in toolleveling the other enchantment works on minecraft tools but not on the super pickaxe of supertools

**Comment by tristankechlo** [comment]
I am sorry, but I can't figure out why the mod does not work sometimes for you.  
There is nothing wrong in the logs,  
and I even tried  installing all the mods, you have on your server

**Comment by gragonfire242002** [comment]
Ok no worries in any case thank you for trying to look for me have a nice day you are that I close the help?
