### ISSUE TITLE
[Fabric] Breaks server side lang entries.

### ISSUE THREAD

**Issue by frikinjay** [tristankechlo/Tool-Leveling#28]
**Describe the bug**
The lang entries no longer properly show the values as you can see in the screenshot below. Using the mod on quilt

**To Reproduce**
1. Download Pack Zero 2.0.9b from modrinth
2. Run a server with the pack
3. Look at logs

**Expected behavior**
To not do whats it doing currently

**Screenshots**
![image](https://user-images.githubusercontent.com/88995340/175267959-9b70498c-0953-4469-8a93-320485d656e9.png)

**Additional context**

**Comment by tristankechlo** [comment]
Thank you for pointing that out, will be fixed in the next update

**Comment by tristankechlo** [comment]
fixed
