### ISSUE TITLE
tool leveling has failed to load correctly: forge 41.0.98

### ISSUE THREAD

**Issue by krjencik** [tristankechlo/Tool-Leveling#31]
**Describe the bug**
Minecraft wont run
**To Reproduce**
1. Go to '...' download forge 41.0.98
2. Click on '....' download this mod ver. 1.3.3
3. Scroll down to '....' run minecraft
4. See error the screen goes black with a message: tool leveling has failed to load correctly

**Expected behavior**
be able to see Minecraft's main menu
**Screenshots**

**Additional context**

**Comment by tristankechlo** [comment]
yeah, forge renamed some things in one of the latest versions, will update the mod soon
forge versions before 41.0.93 should still work

**Comment by tristankechlo** [comment]
should be fixed with newest modversion 1.3.4
