### ISSUE TITLE
Project E enchants please

### ISSUE THREAD

**Issue by domshi** [tristankechlo/Tool-Leveling#33]
**Describe the solution you'd like**
I would like Project E equipments to be added to the items able to be enchanted.

**Describe alternatives you've considered**
teach me how to modify it myself

**Additional context**
These equipments don't currently have ability to be enchanted regularly, so I'm not entirely sure if that will cause additional issues
I can provide mod files if you wish

**Comment by domshi** [comment]
oh, also. I forgot to include I'm running 1.19.2 version

**Comment by tristankechlo** [comment]
I made this mod only to upgrade existing enchantments,  
if the equipment from Project E can not be enchanted then I will not add support for it
