### ISSUE TITLE
Cost calculation problem

### ISSUE THREAD

**Issue by MixhizoR** [tristankechlo/Tool-Leveling#36]
**Describe the bug**
When are you going to upgrade a enchantment, if you put more worth items than cost, it takes much more than cost

**To Reproduce**
1. Enchant an item
2. Put more worth items than cost

**Expected behavior**
decrease worth by cost

**Screenshots**
If applicable, add screenshots to help
![Adsız](https://user-images.githubusercontent.com/39201527/228655935-8436ccc4-96c0-4073-a5dd-c2c18a2cdd88.png)
![Adsız2](https://user-images.githubusercontent.com/39201527/228655947-1b49fa11-4e17-4319-9db5-d9aa0c04df65.png)
 explain your problem.

**Additional context**

**Comment by tristankechlo** [comment]
That's odd,
what minecraft and mod-version are you using?
Forge or Fabric?

**Comment by MixhizoR** [comment]
Fabric 1.19.3 and if I remember correctly, it happened to me in older versions too.

**Comment by tristankechlo** [comment]
Thanks for reporting,
will try to fix this with the next update

**Comment by MixhizoR** [comment]
No no thanks to you. I love your mod.

**Comment by tristankechlo** [comment]
should be fixed with modversion 1.4.5  
currently only for 1.18.2 and 1.19.4
