### ISSUE TITLE
Forge 19.2 - Adding Mats and Block

### ISSUE THREAD

**Issue by xd4rkzghost01** [tristankechlo/Tool-Leveling#38]
**Describe the bug**
Hi there ! I ran into an issue today. I'm making a modpack for myself (hehe) and i was trying to add more items and block to the list. The problem here is when i try to type any new block or item, they seem to not register even if the JSON file is valid.

**Expected behavior**
Try to add new block from other mods : BlueSkies, Undergarden, The Abyss 2, Infernal Expansion, Apotheosis, Scaling Health, Netherrocks, Easy Steel & More, BYG, Forbiden & Arcanus and End Phantasm.
For the moment i only add BlueSkies block (ores and ingots) and nothing is working. Is there a way to add more block? Or a way better than F3+H to find the block tag if i dont have the good one?

**Text Log**
The Item Value (that i'm trying to modify)
[(notepad)item_values.txt](https://github.com/tristankechlo/ToolLeveling/files/11886944/notepad.item_values.txt)

**Additional context**
Help Me? :D

**Comment by tristankechlo** [comment]
What minecraft and modversion are you using?  
  
The file you uploaded is named `notepad.item_values.txt` is this the same in the config folder? It should be named `item_values.json`

**Comment by xd4rkzghost01** [comment]
Wow.. i miss this part ahah !
It's on Forge 19.2 = 43.2.14
Latest Tool Leveling
And Yes, i just rename the JSON text to be available in the GitHub.

**Comment by tristankechlo** [comment]
Did you reload the config after you made changes? (`/toolleveling config reload` or restarting the game)  
Are there any errors in the log when you reload the config?

**Comment by xd4rkzghost01** [comment]
[Sorry im on my phone] 
I'ma gonna check in a hour(n'½) for the Log. I know there no crash/error at the moment, but yes i reload the config and relaunch the game (save/exit->relaunch). Also my pack is about 156+ mod install, mostly Structures, couple Mobs and Adventure. I know that i got Polymorph install (witch can propose multi-recipe for block) if that can help. I'm gonna edit this last post later to add my ModList.

Edit: Despite getting a list of all the mod, i've seen that i was on the wrong....modpack....

![Dummy](https://github.com/tristankechlo/ToolLeveling/assets/63568312/dff11829-ebfa-46e0-a528-cca29b0d5e5b)

I'ma gonne re-try..... sorry bothering you T_T'

RE-Edit: It work....my bad...
Note to other people, don't work on multiple modpack at the same time and open config from different version. Everthing works perfectly.
Ps: I Love your mod :D
