### ISSUE TITLE
Multiple Ingredient Cost

### ISSUE THREAD

**Issue by Gridfreelancer9** [tristankechlo/Tool-Leveling#5]
**Is your feature request related to a problem? Please describe.**
Not really a problem but having multiple different ingredients would allow this to be a more customizable end game item than it already is.

**Describe the solution you'd like**
I'm not gonna ask for infinite amount cause that's crazy. Up to 4 different ingredients would work great since there are already 4 ingredient slots. Keeping the multiplier to be overall would be fine but having individual multipliers would be sick.

**Describe alternatives you've considered**
First idea that came to mind but feels like it would be the "easiest" to implement as there is already some foundation for this idea like the 4 ingredient slots.

**Additional context**
No additional context.

**Comment by tristankechlo** [comment]
That's basicly the plan for the next update.
Plan is to support multiple items, with different worth, as payment items

**Comment by tristankechlo** [comment]
Multiple payment items now possible with newest beta update
[Curseforge](https://www.curseforge.com/minecraft/mc-mods/tool-leveling-plus/files/3227415)
