### ISSUE TITLE
Different upgradeCosts for different enchantments

### ISSUE THREAD

**Issue by Torben8** [tristankechlo/Tool-Leveling#8]
**Is your feature request related to a problem? Please describe.**
Different enchantments have different max stages, like sharpness and looting. It would be nice if upgrading a weapon from sharpness 5 costs as much as upgrading looting 3. 

**Describe the solution you'd like**
Maybe a different baseCost for different enchantments or a different calculation for the upgradeCost based on the max level of the enchantment. So that Looting 4 is just as valuable as sharp 6.

I think this would be a rather big update, I can understand if you don't want to implement this.

**Comment by tristankechlo** [comment]
I think I won't integrate this, but thank you for your idea
